server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.111:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.1.111
    port: 6379
    password: '123456'
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    host: 192.168.1.111 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmdp # 虚拟主机
    username: hmdp # 用户名
    password: 123456 # 密码
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug


mail:
  host: smtp.qq.com
  smtp:
    auth: true
    ssl:
      enable: true
      socketFactory: sf
  transport:
    protocol: smtp

  zhanghao: 167993231@qq.com
  shouquanma: jmygiogbephvcadh


